services:

  postgres:
    image: postgres:17.7-alpine
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    ports:
     - 5432:5432
    labels:
      org.springframework.boot.service-connection: postgres

#Раскомментировать если реализуешь работу с Kafka

#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.7.7
#    restart: always
#    environment:
#      ZOOKEEPER_SERVER_ID: 1
#      ZOOKEEPER_CLIENT_PORT: "2181"
#      ZOOKEEPER_TICK_TIME: "2000"
#      ZOOKEEPER_SERVERS: "zookeeper:22888:23888"
#    ports:
#      - "2181:2181"
#    labels:
#     org.springframework.boot.service-connection: zookeeper
#
#  kafka:
#    image: confluentinc/cp-kafka:7.7.7
#    ports:
#      - 9092:9092
#    labels:
#      org.springframework.boot.service-connection: kafka
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    depends_on:
#      - zookeeper