spring:
  application:
    name: hotel-booking
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: booking
    password: booking
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
